# Generated by Django 4.0.4 on 2022-05-03 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='profile_pic',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
