# Generated by Django 4.0.4 on 2022-05-06 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0002_userprofile_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='event',
            field=models.JSONField(),
        ),
    ]
