# Generated by Django 4.0.4 on 2022-05-02 18:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('django_app', '0004_comment_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='marker',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marker', to=settings.AUTH_USER_MODEL),
        ),
    ]
